### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by iyanmv** [Qiskit-Extensions/qiskit-ibm-experiment#56]
Hello,

I just discovered that the latest version is [0.2.7](https://pypi.org/project/qiskit-ibm-experiment/0.2.7/), but here there is only a release for 0.1.0.

Will you keep releases here as well (like in the rest of qiskit packages) or should I change to PyPI to keep an eye on new releases?

**Comment by iyanmv** [comment]
Sorry to bother again, but can @anyone have a look at this? Should be straightforward to fix.

**Comment by gadial** [comment]
By "release" do you mean a "stable/0.x" branch? We should have this from 0.3 onwards (0.3 will be the stable version which supports the current changes being done in `qiskit-experiments`).

**Comment by iyanmv** [comment]
By "release" a mean a consistent way of knowing the last stable version of the project from Github so I can create a proper package for a distribution. For example, [the last release tag in Github](https://github.com/Qiskit/qiskit-ibm-experiment/releases) is 0.1.0, while [the last tag](https://github.com/Qiskit/qiskit-ibm-experiment/tags) is 0.2.8, which is the one used by [PyPI](https://pypi.org/project/qiskit-ibm-experiment/). Should I package 0.1.0 or 0.2.8? Other qiskit projects always announce stable releases in github as release tag and there is no confusion.

**Comment by 1ucian0** [comment]
Thanks to @qiskit-bot (actually, thanks to @mtreinish and @gadial for setting it up) now releases in GitHub are included. Feel free to comment or reopen you consider this issues still not done.
