### ISSUE TITLE
Please link to https://qiskit.org/ecosystem/ibm-experiment/ in GitHub's About section

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit-Extensions/qiskit-ibm-experiment#66]
It is useful to have the link to the project docs on the GitHub home page for this repo.

To fix this, go to the "Code"/home page of the repo. Then click the wheel on the "about" section on the right. Set the website to https://qiskit.org/ecosystem/ibm-experiment/.

![Screenshot 2023-05-15 at 9 55 20 AM](https://github.com/Qiskit-Partners/qiskit-aqt-provider/assets/14852634/5085a3cd-e3d8-43e1-996f-be9e3c9d6147)

Thanks!

[BLOCKED BY https://github.com/Qiskit/qiskit-ibm-experiment/pull/61]

**Comment by Eric-Arellano** [comment]
This is no longer blocked: https://qiskit.org/ecosystem/ibm-experiment/ now works 🎉

**Comment by Eric-Arellano** [comment]
Hey @gadial , bump

**Comment by 1ucian0** [comment]
done!

![Screenshot 2023-10-16 at 09 27 42](https://github.com/Qiskit-Extensions/qiskit-ibm-experiment/assets/766693/0c5975bd-b777-4260-b3f5-97d6e8c2486e)
