### ISSUE TITLE
Set up GitHub Pages

### ISSUE THREAD

**Issue by arnaucasau** [Qiskit-Extensions/qiskit-ibm-experiment#97]
### Instructions 
The project now has the documentation deployed in a branch called [gh-pages](https://github.com/Qiskit-Extensions/qiskit-ibm-experiment/tree/gh-pages), but we need to set up the repo to use GitHub Pages by following the next 5 steps:

1. Navigate to your site's repository
2. Click `Settings`
3. Go to `Pages`
4. Select `Deploy from a branch`, under the `Source` section on `Build and deployment`
5. Select the `gh-pages` branch and the `/ (root)` folder in the `Branch` section on `Build and deployment`

![GitHubPages-example](https://github.com/Qiskit/ecosystem/assets/47946624/520f4f0c-905a-4a4f-b918-a580a953e80d)

The default URL where you can find your site is https://qiskit-extensions.github.io/qiskit-ibm-experiment

For further information, you can see the [GitHub Pages Quickstart](https://docs.github.com/en/pages/quickstart#creating-your-website) and https://github.com/Qiskit/ecosystem/issues/578.

**Comment by coruscating** [comment]
Done and updated the website URL in the About section, thanks for pointing this out!
